### ISSUE TITLE
Add support for DS3/4 And Xbox controllers

### ISSUE THREAD

**Issue by danipopnhari** [djhackersdev/bemanitools#267]
i'm a ds4 user that needs help, because i play pop'n music with a controller, and when i try to bind inputs with his config program, it doesnt work.

**Comment by danipopnhari** [comment]
it only binds with keyboards, or arcade style controllers, not with xbox/DS3/4 controllers.

**Comment by icex2** [comment]
I asked around and get the following reports:
- DS3 wired with Sony driver works.
- DS4 wired using the generic Microsoft drivers (shows up as "Wireless Controller" in the game controller configuration) does not work.
- Xbox controller 1914 using the wireless adapter 1790 also works fine

I am not aware of a large user base and need to support a wider range of controllers and players regarding that. Have a look at the apparently existing options. I am also not aware of anyone having this on their roadmap to work on. However, if someone else wants to pick this up, they are free to submit a PR and we have a look at that to get support upstreamed.
